const api = async (path, options={}) => { const r=await fetch('/api/'+path,options); if(!r.ok) throw Error((await r.json()).error||'Terjadi kesalahan'); return r.status===204?null:r.json(); };
const modal=document.getElementById('modal');
document.getElementById('menuToggle').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
document.getElementById('newOrder').onclick=()=>modal.classList.add('show');
document.getElementById('closeModal').onclick=()=>modal.classList.remove('show');
modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};
document.querySelector('.modal').onsubmit=async e=>{e.preventDefault();try{const [cs,ss]=await Promise.all([api('customers'),api('services')]);const f=new FormData(e.target);await api('orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer_id:cs[0].id,service_id:ss[0].id,weight:f.get('weight')||1,status:'Diproses',payment_status:'Belum Lunas'})});alert('Pesanan berhasil disimpan');location.reload()}catch(x){alert(x.message)}};
const names={dashboard:'Dashboard',orders:'Pesanan',customers:'Pelanggan',services:'Layanan & Harga',payments:'Pembayaran',reports:'Laporan',staff:'Karyawan',settings:'Pengaturan'};
const esc=v=>String(v??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function page(type){document.getElementById('pageTitle').textContent=names[type];if(type==='dashboard'){location.reload();return}const fields={customers:['Nama','Telepon','Alamat'],services:['Nama layanan','Harga/kg','Durasi'],staff:['Nama','Peran','Telepon'],orders:['Kode','Pelanggan','Layanan','Berat','Status','Pembayaran'],payments:['Kode','Pelanggan','Total','Status']}[type]||[];document.querySelector('.content').innerHTML=`<div class="date-line"><p>Kelola data ${names[type].toLowerCase()}.</p><button class="new-order" id="addData">＋ Tambah data</button></div><section class="panel recent"><div class="panel-head"><h3>Data ${names[type]}</h3><button class="outline-button" onclick="page('${type}')">↻ Muat ulang</button></div><div class="table-wrap"><table><thead><tr>${fields.map(x=>`<th>${x.toUpperCase()}</th>`).join('')}<th>AKSI</th></tr></thead><tbody id="dataRows"><tr><td colspan="8">Memuat...</td></tr></tbody></table></div></section>`;try{const data=await api(type);document.getElementById('dataRows').innerHTML=data.map(x=>{let cells=type==='orders'||type==='payments'?(type==='orders'?[x.code,x.customer,x.service,x.weight+' kg',x.status,x.payment_status]:[x.code,x.customer,'Rp'+Number(x.total).toLocaleString('id-ID'),x.payment_status]):[x.name,x.phone||x.price,x.address||x.duration||x.role];return `<tr>${cells.map(v=>`<td>${esc(v)}</td>`).join('')}<td><button class="delete-row" data-id="${x.id}">Hapus</button></td></tr>`}).join('')||'<tr><td>Belum ada data</td></tr>';document.querySelectorAll('.delete-row').forEach(b=>b.onclick=async()=>{if(confirm('Hapus data ini?')){await api(type+'/'+b.dataset.id,{method:'DELETE'});page(type)}})}catch(x){document.getElementById('dataRows').innerHTML=`<tr><td>${esc(x.message)}</td></tr>`}document.getElementById('addData').onclick=()=>alert('Gunakan tombol Pesanan baru untuk order. CRUD data master tersedia melalui API.')}
document.querySelectorAll('.nav-item').forEach(a=>a.onclick=e=>{e.preventDefault();document.querySelector('.nav-item.active')?.classList.remove('active');a.classList.add('active');page(a.dataset.page);document.getElementById('sidebar').classList.remove('open')});
document.getElementById('allOrders')?.addEventListener('click',()=>page('orders'));
