const express=require('express');const mysql=require('mysql2/promise');const path=require('path');
const app=express(),port=process.env.PORT||3000;let db;
const q=(sql,params=[])=>db.execute(sql,params);const rows=async(sql,p=[])=>{const [r]=await q(sql,p);return r};
const h=fn=>(req,res)=>fn(req,res).catch(e=>{console.error('API error:',e.message||e);if(!res.headersSent)res.status(500).json({error:'Terjadi kesalahan server'})});
async function seed(){await db.query(`CREATE TABLE IF NOT EXISTS customers(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,phone VARCHAR(30) NOT NULL,address VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS services(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,price DECIMAL(12,2) NOT NULL,duration VARCHAR(50) NOT NULL,active BOOLEAN DEFAULT TRUE);CREATE TABLE IF NOT EXISTS staff(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,role VARCHAR(80) NOT NULL,phone VARCHAR(30) NOT NULL);CREATE TABLE IF NOT EXISTS orders(id INT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(30) UNIQUE,customer_id INT NOT NULL,service_id INT NOT NULL,weight DECIMAL(6,2) NOT NULL,status ENUM('Diproses','Menunggu diambil','Selesai') DEFAULT 'Diproses',payment_status ENUM('Belum Lunas','Lunas') DEFAULT 'Belum Lunas',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES customers(id),FOREIGN KEY(service_id) REFERENCES services(id));`);let count=(await rows('SELECT COUNT(*) n FROM customers'))[0].n;if(!count){await q("INSERT INTO customers(name,phone,address) VALUES ('Siti Aminah','0812-0000-2187','Jl. Melati No. 10'),('Budi Ramadhan','0813-0000-4521','Jl. Mawar No. 8'),('Dewi Permata','0821-0000-7320','Jl. Anggrek No. 21')");await q("INSERT INTO services(name,price,duration) VALUES ('Cuci Kering Lipat',7000,'2–3 hari'),('Cuci Setrika',7000,'2–3 hari'),('Express',14000,'1 hari')");await q("INSERT INTO staff(name,role,phone) VALUES ('Andi Rahman','Administrator','0812-3456-7890'),('Rina Kusuma','Kasir','0812-9876-1234')");await q("INSERT INTO orders(code,customer_id,service_id,weight,status,payment_status) VALUES ('LD-1048',1,1,4.5,'Diproses','Lunas'),('LD-1047',2,3,2,'Menunggu diambil','Belum Lunas'),('LD-1046',3,2,6,'Selesai','Lunas')")}}
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));app.get('/api/health',(req,res)=>res.json({ok:true}));
const orderBase=`SELECT o.*,c.name customer,c.phone,s.name service,s.price,ROUND(o.weight*s.price) total,IF(o.payment_status='Lunas','Tunai','Belum dibayar') payment_method FROM orders o JOIN customers c ON c.id=o.customer_id JOIN services s ON s.id=o.service_id `;
const orderSql=orderBase+'ORDER BY o.id DESC';
app.get('/api/dashboard',h(async(req,res)=>{let orders=await rows(orderSql),customers=await rows('SELECT c.*,COUNT(o.id) order_count FROM customers c LEFT JOIN orders o ON c.id=o.customer_id GROUP BY c.id ORDER BY c.id DESC'),services=await rows('SELECT * FROM services ORDER BY id DESC'),staff=await rows('SELECT * FROM staff ORDER BY id DESC');let sum={orders:orders.length,process:orders.filter(x=>x.status==='Diproses').length,waiting:orders.filter(x=>x.status==='Menunggu diambil').length,done:orders.filter(x=>x.status==='Selesai').length,customers:customers.length,revenue:orders.filter(x=>x.payment_status==='Lunas').reduce((n,x)=>n+Number(x.total),0)};res.json({summary:sum,orders,customers,services,staff,payments:orders})}));
app.get('/api/:type',h(async(req,res)=>{let sql={customers:'SELECT c.*,COUNT(o.id) order_count FROM customers c LEFT JOIN orders o ON c.id=o.customer_id GROUP BY c.id ORDER BY c.id DESC',services:'SELECT * FROM services ORDER BY id DESC',staff:'SELECT * FROM staff ORDER BY id DESC',orders:orderSql,payments:orderSql}[req.params.type];if(!sql)return res.status(404).json({error:'Data tidak ditemukan'});res.json(await rows(sql))}));
app.get('/api/customers/:id/orders',h(async(req,res)=>{let cs=await rows('SELECT c.*,COUNT(o.id) order_count FROM customers c LEFT JOIN orders o ON c.id=o.customer_id WHERE c.id=? GROUP BY c.id',[req.params.id]);if(!cs.length)return res.status(404).json({error:'Pelanggan tidak ditemukan'});res.json({customer:cs[0],orders:await rows(orderBase+'WHERE o.customer_id=? ORDER BY o.id DESC',[req.params.id])})}));
const config={customers:{fields:['name','phone','address'],table:'customers'},services:{fields:['name','price','duration'],table:'services'},staff:{fields:['name','role','phone'],table:'staff'},orders:{fields:['customer_id','service_id','weight','status','payment_status'],table:'orders'}};
app.post('/api/:type',h(async(req,res)=>{let c=config[req.params.type];if(!c)return res.status(404).end();let v=c.fields.map(f=>req.body[f]);if(v.slice(0,3).some(x=>x===undefined||x===''))return res.status(400).json({error:'Data wajib belum lengkap'});let f2=c.fields.filter((f,i)=>v[i]!==undefined&&v[i]!=='');if(c.table==='orders'){let [[x]]=await q('SELECT COALESCE(MAX(id),0)+1046 id FROM orders');await q(`INSERT INTO orders(code,${f2.join(',')}) VALUES (?,${f2.map(()=>'?').join(',')})`,['LD-'+x.id,...f2.map(f=>req.body[f])])}else await q(`INSERT INTO ${c.table}(${f2.join(',')}) VALUES (${f2.map(()=>'?').join(',')})`,f2.map(f=>req.body[f]));res.status(201).json({ok:true})}));
app.put('/api/:type/:id',h(async(req,res)=>{let c=config[req.params.type];if(!c)return res.status(404).end();let f2=c.fields.filter(f=>req.body[f]!==undefined&&req.body[f]!=='');if(!f2.length)return res.status(400).json({error:'Tidak ada data untuk diubah'});if(c.table==='orders'&&req.body.payment_status&&req.body.payment_status!=='Lunas'){let cur=await rows('SELECT payment_status FROM orders WHERE id=?',[req.params.id]);if(cur.length&&cur[0].payment_status==='Lunas')return res.status(400).json({error:'Pembayaran yang sudah lunas tidak dapat diubah kembali'})}await q(`UPDATE ${c.table} SET ${f2.map(f=>f+'=?').join(',')} WHERE id=?`,[...f2.map(f=>req.body[f]),req.params.id]);res.json({ok:true})}));
app.delete('/api/:type/:id',h(async(req,res)=>{let c=config[req.params.type];if(!c)return res.status(404).end();try{await q(`DELETE FROM ${c.table} WHERE id=?`,[req.params.id]);res.status(204).end()}catch(e){res.status(400).json({error:'Data masih dipakai oleh pesanan'})}}));
async function start(){db=await mysql.createPool({host:process.env.DB_HOST||'db',user:process.env.DB_USER||'laundry',password:process.env.DB_PASSWORD||'laundry_secret',database:process.env.DB_NAME||'laundry_db',waitForConnections:true,connectionLimit:10,multipleStatements:true});await seed();app.listen(port,()=>console.log('Laundry system running on '+port))}start().catch(e=>{console.error(e);setTimeout(start,5000)});
